# action.yml
name: 'NetCDF Test Action'
description: 'An action to run tests for the various netCDF projects'
inputs:
  repo-type:
    description: 'Specify if this is one of the root netcdf repos. c, fortran, cxx4, java'
    required: false
  build-system:
    description: 'Build System to test. cmake, autotools, both'
    required: true
  ctest-repeat:
    description: 'Number of times ctest will try to repeat until success. default: 3'
    required: false
  hdf5-version:
    description: 'HDF5 Version to test against. Currently no support for versions with a tag identifier, e.g. 1.14.0-1: default 1.14.6'
    required: false
  run-c:
    description: 'Whether or not the C tests should be run.'
    required: true
  c-branch:
    description: 'Branch or tag of netCDF-C to use, default is main *or* current commit'
    required: false
  c-compiler:
    description: 'C compiler to use: gcc, clang, mpicc (from openmpich)'
    required: true
  cmake-c-options:
    description: 'Additional options to pass to cmake'
    required: false
  autotools-c-options:
    description: 'Additional options to pass to autotools'
    required: false
  mpich-version:
    description: 'mpich version to install.  If none specified, underlying package-manager provided version used.'
    required: false
  run-fortran:
    description: 'Whether or not the Fortran tests should be run.'
    required: true
  fortran-branch:
    description: 'Branch or tag of netCDF-Fortran to use, default is main *or* current commit'
    required: false
  run-java:
    description: 'Whether or not the Java tests should be run.'
    required: false
  java-branch:
    description: 'Branch or tag of netCDF-Java to use, default is maint-5.x'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO_TYPE: ${{ inputs.repo-type }}
    USE_BUILDSYSTEM: ${{ inputs.build-system }}
    CTEST_REPEAT: ${{ inputs.ctest-repeat || 3 }}
    H5VER: ${{ inputs.hdf5-version }}
    RUNC: ${{ inputs.run-c }}
    CBRANCH: ${{ inputs.c-branch }}
    USE_CC: ${{ inputs.c-compiler }}
    MPICHVER: ${{ inputs.mpich-version || 'default' }}
    RUNF: ${{ inputs.run-fortran }}
    FBRANCH: ${{ inputs.fortran-branch }}
    RUNJAVA: ${{ inputs.run-java || 'FALSE' }}
    JAVABRANCH: ${{ inputs.java-branch || 'maint-5.x' }}
    CMAKE_COPTS: ${{ inputs.cmake-c-options || '' }}
    AC_COPTS: ${{ inputs.autotools-c-options || '' }}
